import type { Metadata } from 'next';
export const metadata: Metadata = {title: 'Bigger Fish Privacy Policy', description: 'Bigger Fish anonymous gameplay summaries and local progress.'};
export default function BiggerFishPrivacy() {
  return <main style={{maxWidth:760,margin:'0 auto',padding:'40px 24px',lineHeight:1.7}}>
    <h1>Bigger Fish Privacy Policy</h1><p>Last updated: October 4, 2026</p>
    <h2>Local game progress</h2><p>Bigger Fish saves cleared levels, best times, and instruction progress on your device. It has no accounts or ads. Deleting the app removes its local information; it may also be included in your own device backups, which we cannot access.</p>
    <h2>Anonymous gameplay summaries</h2><p>To improve the game, supported builds may send first-party gameplay summaries to BrightBench. These describe the world, level, game-content setup and seed, app version/build and distribution channel; whether a run was won, lost, quit or abandoned; attempts before a first clear; gameplay duration and circuits; fish eaten by the player and other fish; near-equal catches and bounces; time spent in cleanup or without enough growth opportunities; and size/count summaries and cause at death. A growth-path check estimates whether remaining fish could supply enough growth; it does not guarantee a safe route to victory. Some progression milestones are recorded once per installation using markers that stay on the device.</p>
    <h2>No individual tracking</h2><p>We do not send a player, installation, advertising, or session identifier, exact real-world play timestamps, device model, location, contacts, or movement trajectories. We do not link reports into individual player histories or combine them with other apps. There are no third-party analytics or advertising SDKs. Attempt counters and milestone markers remain on-device; only summaries are sent.</p>
    <h2>How summaries are handled</h2><p>The receiver validates summaries and immediately turns them into aggregate counts, sums, and histograms grouped by game content and build. It does not store individual request bodies. Aggregate daily data expires after 90 days; the day is the server receive date, not when you played. Reports are used to improve level difficulty and gameplay, not advertising. Batches that fail to send are dropped rather than retried with identifiers. The game works offline.</p>
    <h2>Service providers</h2><p>Brightbench.app runs on Vercel and uses Upstash to store aggregate counters. These providers process network connections, including IP addresses, to deliver the service. The analytics application does not write IP addresses or request bodies to its logs. Provider-level operational logging may occur under the providers’ policies.</p>
    <h2>Beta feedback and contact</h2><p>TestFlight feedback and crash reporting are provided separately by Apple. If you send feedback or email us, we receive the information you choose to include and use it to help you. Contact <a href="mailto:support@brightbench.app">support@brightbench.app</a> with questions or deletion requests about information you have sent directly.</p>
    <h2>Changes</h2><p>We will update this policy before shipping changes to the information collected. Collection remains disabled in builds until the matching endpoint and disclosures are ready.</p>
  </main>;
}
